### ISSUE TITLE
question about cell order

### ISSUE THREAD

**Issue by Xieeeee** [ma-compbio/Higashi#32]
Hi Ruochi,
I am a little bit confused about the order of cells in fast higashi data. In `fetch_cell_embedding` the default is `restore_order=False`, and in the wiki it mentions cells with high quality / pass qc filtering would be put in front of 'bad' cells. 

Now if I only want to check the embedding of those pass qc cells, I do `get_qc()` to obtained those who pass qc: `kept, read_count_all = wrapper.get_qc()`

Does the order in `kept` the same order of input data, or has it been reordered?

Best,
Yang

**Comment by ruochiz** [comment]
kept and read_count_all should have the same order as the input data.

**Comment by Xieeeee** [comment]
OK, thanks!

**Comment by Xieeeee** [comment]
Hi Ruochi,
Sorry for disturbing again. when we say "order of input data", does it mean the order of barcodes (from 0 to n, I record it in an array `cellid`), or the order of barcodes first appear in input data (could be 0, 32, 5, 11...)? 

I tried to filter out those cells that didn't pass QC: `cellid[kept.astype(bool)] ` and then regenerate the input file to make sure it only contains the barcodes past qc. But when loading the new input file, not all the cells are defined as pass qc, and the ratio of "good cells" mimics the unfiltered data.

**Comment by ruochiz** [comment]
Hey, What you did using `cellid[kept.astype(bool)]` is correct. The behavior is also expected, because in the current code, the good_qc of cells are defined based on quantile, so things like this can happen. 

The logic goes like this:
1. calculate n_counts per chrom. If there are more than 50% of the cells that have n_counts > number of bins in this chromosome, we use n_counts > n_bin as the metric. If not, we use n_counts > np.quantile(n_counts, 0.5) as the metric. This metric is per chromosome.
2. Good qc cells are cells that pass metric for all chromosomes.

So, if there are fewer than 50% of the cells that have n_counts > n_bins on one or some of the chromosomes, the metric is defined based on quantile, which means cells can be further filtered.

**Comment by Xieeeee** [comment]
Thanks for the clarification!
