### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by tarak77** [ma-compbio/Higashi#4]
Hi Ruochi,
This is an excellent time to come across Higashi. 
I have not yet started installing and working on the method..but I wanted to ask whether it will be possible to find subclusters(using TADs, compartments) in a single cell data set with ~100 cells? is that number too low?

Thanks!

**Comment by ruochiz** [comment]
Hi,

Thanks for your interest. It would be possible, especially when the coverage for each cell is relatively higher. For a dataset with smaller number of cells, It would also be easier to define subclusters based on one chromosome or a part of the chromosome of interest instead of whole genome. But of course, it depends on the composition of the cell population as well.

**Comment by tarak77** [comment]
Ok I will try it now

**Comment by ruochiz** [comment]
Great. If you don't mind, could you wait for a day or so? I'm updating the code base with a major speed improvement today, which I believe would enhance your experiences with Higashi a lot. :smile:

**Comment by tarak77** [comment]
Sounds good! I will just try using scHiCluster for today then.
